Improve packaging (init script for rhel, gc.log, elasticsearch data dir...)

diff --git a/distribution/rpm/src/main/packaging/init.d/cassandra b/distribution/rpm/src/main/packaging/init.d/cassandra
--- a/distribution/rpm/src/main/packaging/init.d/cassandra
+++ b/distribution/rpm/src/main/packaging/init.d/cassandra
@@ -1,163 +1,203 @@
-#! /bin/sh
+#!/bin/bash
+#
+# cassandra <summary>
+#
+# chkconfig:   2345 80 20
+# description: Starts and stops a single elassandra instance on this system
+#
+
 ### BEGIN INIT INFO
-# Provides:          cassandra
-# Required-Start:    $remote_fs $network $named $time
-# Required-Stop:     $remote_fs $network $named $time
-# Should-Start:      ntp mdadm
-# Should-Stop:       ntp mdadm
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: distributed storage system for structured data
-# Description:       Cassandra is a distributed (peer-to-peer) system for
-#                    the management and storage of structured data.
+# Provides: Elassandra
+# Required-Start: $network $named
+# Required-Stop: $network $named
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: This service manages the elassandra daemon
+# Description: Elassandra is a very scalable, schema-free and high-performance search solution supporting multi-tenancy and near realtime search.
 ### END INIT INFO
 
-# Author: Eric Evans <eevans@racklabs.com>
-# Modified by <barthelemy.delemotte@gmail.com> for Elassandra
+#
+# init.d / servicectl compatibility (openSUSE)
+#
+if [ -f /etc/rc.status ]; then
+    . /etc/rc.status
+    rc_reset
+fi
 
-DESC="Cassandra"
-NAME=cassandra
-PIDFILE=${packaging.elassandra.pid.dir}/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
-CONFDIR=${packaging.elassandra.conf.dir}
-WAIT_FOR_START=10
+#
+# Source function library.
+#
+if [ -f /etc/rc.d/init.d/functions ]; then
+    . /etc/rc.d/init.d/functions
+fi
+
+# Sets the default values for elassandra variables used in this script
 CASSANDRA_HOME=${packaging.elassandra.home.dir}
-CASSANDRA_CONF=$CONFDIR
-FD_LIMIT=100000
+CASSANDRA_USER="cassandra"
+CASSANDRA_GROUP="cassandra"
+CASSANDRA_LOGDIR="/var/log/cassandra"
 
-[ -e $CASSANDRA_CONF/cassandra.yaml ] || exit 0
-[ -e $CASSANDRA_CONF/cassandra-env.sh ] || exit 0
+MAX_OPEN_FILES=100000
+MAX_MAP_COUNT=1048575
+MAX_LOCKED_MEMORY=unlimited
+MAX_AS=unlimited
+MAX_NPROC=32768
 
-# Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+PID_DIR="${packaging.elassandra.pid.dir}"
 
-# Export ELASTICSEARCH_ENABLE, if set
+# Source the default env file
+ES_ENV_FILE="/etc/default/cassandra"
+if [ -f "/etc/default/cassandra" ]; then
+    . "/etc/default/cassandra"
+fi
+
+# Export some variables needed if defined in /etc/default/cassandra
+export CASSANDRA_LOGDIR
+[ -n "$EXTRA_CLASSPATH" ] && export EXTRA_CLASSPATH
 [ -n "$CASSANDRA_DAEMON" ] && export CASSANDRA_DAEMON
-
-# Export JAVA_HOME, if set.
+[ -n "$JVM_OPTS" ] && export JVM_OPTS
 [ -n "$JAVA_HOME" ] && export JAVA_HOME
+[ -n "$CASSANDRA_CONF" ] && export CASSANDRA_CONF
 
-# Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
 
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
-. /lib/lsb/init-functions
+if [ "$CASSANDRA_USER" != "cassandra" ] || [ "$CASSANDRA_GROUP" != "cassandra" ]; then
+    echo "WARNING: CASSANDRA_USER and CASSANDRA_GROUP are deprecated and will be removed in the next major version of Elassandra, got: [$CASSANDRA_USER:$CASSANDRA_GROUP]"
+fi
 
-#
-# Function that returns 0 if process is running, or nonzero if not.
-#
-# The nonzero value is 3 if the process is simply not running, and 1 if the
-# process is not running but the pidfile exists (to match the exit codes for
-# the "status" command; see LSB core spec 3.1, section 20.2)
-#
-CMD_PATT="Dcassandra-pidfile=.*cassandra\.pid"
-is_running()
-{
-    if [ -f $PIDFILE ]; then
-        pid=`cat $PIDFILE`
-        grep -Eq "$CMD_PATT" "/proc/$pid/cmdline" 2>/dev/null && return 0
-        return 1
+# CONF_FILE setting was removed
+if [ ! -z "$CONF_FILE" ]; then
+    echo "CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed."
+    exit 1
+fi
+
+exec="/usr/sbin/cassandra"
+prog="cassandra"
+pidfile="$PID_DIR/${prog}.pid"
+
+lockfile=/var/lock/subsys/$prog
+
+# backwards compatibility for old config sysconfig files, pre 0.90.1
+if [ -n $USER ] && [ -z $CASSANDRA_USER ] ; then
+   CASSANDRA_USER=$USER
+fi
+
+if [ ! -x "$exec" ]; then
+    echo "The cassandra startup script does not exists or it is not executable, tried: $exec"
+    exit 1
+fi
+
+checkJava() {
+    if [ -x "$JAVA_HOME/bin/java" ]; then
+        JAVA="$JAVA_HOME/bin/java"
+    else
+        JAVA=`which java`
     fi
-    return 3
+
+    if [ ! -x "$JAVA" ]; then
+        echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
+        exit 1
+    fi
 }
 
-#
-# Function that starts the daemon/service
-#
-do_start()
-{
-    # Return
-    #   0 if daemon has been started
-    #   1 if daemon was already running
-    #   2 if daemon could not be started
+start() {
+    checkJava
+    [ -x $exec ] || exit 5
 
-    ulimit -l unlimited
-    ulimit -n "$FD_LIMIT"
+    if [ -n "$MAX_OPEN_FILES" ]; then
+        ulimit -n $MAX_OPEN_FILES
+    fi
+    if [ -n "$MAX_LOCKED_MEMORY" ]; then
+        ulimit -l $MAX_LOCKED_MEMORY
+    fi
+    if [ -n "$MAX_NPROC" ]; then
+        ulimit -u $MAX_NPROC
+    fi
+    if [ -n "$MAX_AS" ]; then
+        ulimit -v $MAX_AS
+    fi
+    if [ -n "$MAX_MAP_COUNT" -a -f /proc/sys/vm/max_map_count ]; then
+        sysctl -q -w vm.max_map_count=$MAX_MAP_COUNT
+    fi
 
-    cassandra_home=`getent passwd cassandra | awk -F ':' '{ print $6; }'`
-    heap_dump_f="$cassandra_home/java_`date +%s`.hprof"
-    error_log_f="$cassandra_home/hs_err_`date +%s`.log"
+    # Ensure that the PID_DIR exists (it is cleaned at OS startup time)
+    if [ -n "$PID_DIR" ] && [ ! -e "$PID_DIR" ]; then
+        mkdir -p "$PID_DIR" && chown "$CASSANDRA_USER":"$CASSANDRA_GROUP" "$PID_DIR"
+    fi
+    if [ -n "$pidfile" ] && [ ! -e "$pidfile" ]; then
+        touch "$pidfile" && chown "$CASSANDRA_USER":"$CASSANDRA_GROUP" "$pidfile"
+    fi
 
-    [ -e `dirname "$PIDFILE"` ] || \
-        install -d -ocassandra -gcassandra -m755 `dirname $PIDFILE`
-
-
-
-    start-stop-daemon -S -c cassandra -a /usr/sbin/cassandra -q -p "$PIDFILE" -t >/dev/null || return 1
-
-    start-stop-daemon -S -c cassandra -a /usr/sbin/cassandra -b -p "$PIDFILE" -- \
-        -p "$PIDFILE" -H "$heap_dump_f" -E "$error_log_f" >/dev/null || return 2
-
+    cd $CASSANDRA_HOME
+    echo -n $"Starting $prog: "
+    # if not running, start it up here, usually something like "daemon $exec"
+    daemon --user $CASSANDRA_USER --pidfile $pidfile $exec -p $pidfile
+    retval=$?
+    echo
+    [ $retval -eq 0 ] && touch $lockfile
+    return $retval
 }
 
-#
-# Function that stops the daemon/service
-#
-do_stop()
-{
-    # Return
-    #   0 if daemon has been stopped
-    #   1 if daemon was already stopped
-    #   2 if daemon could not be stopped
-    #   other if a failure occurred
-    start-stop-daemon -K -p "$PIDFILE" -R TERM/30/KILL/5 >/dev/null
-    RET=$?
-    rm -f "$PIDFILE"
-    return $RET
+stop() {
+    echo -n $"Stopping $prog: "
+    # stop it here, often "killproc $prog"
+    killproc -p $pidfile -d 86400 $prog
+    retval=$?
+    echo
+    [ $retval -eq 0 ] && rm -f $lockfile
+    return $retval
 }
+
+restart() {
+    stop
+    start
+}
+
+reload() {
+    restart
+}
+
+force_reload() {
+    restart
+}
+
+rh_status() {
+    # run checks to determine if the service is running or use generic status
+    status -p $pidfile $prog
+}
+
+rh_status_q() {
+    rh_status >/dev/null 2>&1
+}
+
 
 case "$1" in
-  start)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-    do_start
-    case "$?" in
-        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-    esac
-    ;;
-  stop)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-    do_stop
-    case "$?" in
-        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-    esac
-    ;;
-  restart|force-reload)
-    log_daemon_msg "Restarting $DESC" "$NAME"
-    do_stop
-    case "$?" in
-      0|1)
-        do_start
-        case "$?" in
-            0) log_end_msg 0 ;;
-            1) log_end_msg 1 ;; # Old process is still running
-            *) log_end_msg 1 ;; # Failed to start
-        esac
+    start)
+        rh_status_q && exit 0
+        $1
         ;;
-      *)
-        # Failed to stop
-        log_end_msg 1
+    stop)
+        rh_status_q || exit 0
+        $1
         ;;
-    esac
-    ;;
-  status)
-    is_running
-    stat=$?
-    case "$stat" in
-      0) log_success_msg "$DESC is running" ;;
-      1) log_failure_msg "could not access pidfile for $DESC" ;;
-      *) log_success_msg "$DESC is not running" ;;
-    esac
-    exit "$stat"
-    ;;
-  *)
-    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
-    exit 3
-    ;;
+    restart)
+        $1
+        ;;
+    reload)
+        rh_status_q || exit 7
+        $1
+        ;;
+    force-reload)
+        force_reload
+        ;;
+    status)
+        rh_status
+        ;;
+    condrestart|try-restart)
+        rh_status_q || exit 0
+        restart
+        ;;
+    *)
+        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
+        exit 2
 esac
-
-:
-
-# vi:ai sw=4 ts=4 tw=0 et
+exit $?
