fixup plugin utility

diff --git a/distribution/src/bin2/elasticsearch-env b/distribution/src/bin2/elasticsearch-env
--- a/distribution/src/bin2/elasticsearch-env
+++ b/distribution/src/bin2/elasticsearch-env
@@ -41,11 +41,12 @@ if [ -x "$JAVA_HOME/bin/java" ]; then
 else
   set +e
   JAVA=`which java`
+  echo "warning: Falling back to java on path. This behavior is deprecated. Specify JAVA_HOME"
   set -e
 fi
 
 if [ ! -x "$JAVA" ]; then
-  echo "could not find java; set JAVA_HOME or ensure java is in PATH"
+  echo "could not find java; set JAVA_HOME" >&2
   exit 1
 fi
 
@@ -63,7 +64,7 @@ if [ ! -z "$JAVA_OPTS" ]; then
 fi
 
 # check the Java version
-"$JAVA" -cp "$ES_CLASSPATH" org.elasticsearch.tools.launchers.JavaVersionChecker
+"$JAVA" -cp "$ES_CLASSPATH" org.elasticsearch.tools.java_version_checker.JavaVersionChecker
 
 export HOSTNAME=$HOSTNAME
 
@@ -78,14 +79,9 @@ fi
 # now make ES_PATH_CONF absolute
 ES_PATH_CONF=`cd "$ES_PATH_CONF"; pwd`
 
+ES_DISTRIBUTION_FLAVOR=${es.distribution.flavor}
+ES_DISTRIBUTION_TYPE=${es.distribution.type}
+
 if [ -z "$ES_TMPDIR" ]; then
-  set +e
-  mktemp --version 2>&1 | grep coreutils > /dev/null
-  mktemp_coreutils=$?
-  set -e
-  if [ $mktemp_coreutils -eq 0 ]; then
-    ES_TMPDIR=`mktemp -d --tmpdir "elasticsearch.XXXXXXXX"`
-  else
-    ES_TMPDIR=`mktemp -d -t elasticsearch`
-  fi
+  ES_TMPDIR=`"$JAVA" -cp "$ES_CLASSPATH" org.elasticsearch.tools.launchers.TempDirectory`
 fi
